# Generated by Django 5.0.1 on 2024-01-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
